# Multi-Agent Synchronization Configuration
# Qubic AI Compute Layer Project

project:
  name: "Qubic AI Compute Layer"
  version: "1.0.0"
  start_date: "2025-01-20"
  
sync_protocol:
  update_frequency: "5 minutes"        # 基礎同步頻率
  realtime_events: "30 seconds"       # 即時事件同步
  conflict_resolution: "central_coordinator"
  priority_system: "weighted_priority"
  max_sync_retries: 3
  sync_timeout: "2 minutes"

communication_channels:
  - type: "shared_state_file"
    path: ".cursor/shared-state/project-state.json"
    update_frequency: "continuous"
    access_level: "read_write"
    
  - type: "task_board"
    path: ".cursor/shared-state/task-board.md"
    update_frequency: "hourly"
    access_level: "collaborative"
    
  - type: "daily_standup"
    path: ".cursor/shared-state/daily-standup.md"
    update_frequency: "daily"
    access_level: "append_only"
    
  - type: "conflict_log"
    path: ".cursor/shared-state/conflicts.md"
    update_frequency: "on_conflict"
    access_level: "coordinator_only"
    
  - type: "decision_log"
    path: ".cursor/shared-state/decisions.md"
    update_frequency: "on_decision"
    access_level: "coordinator_only"

# 智能體工作空間分配
agent_workspaces:
  central_coordinator:
    priority: "highest"
    authority_level: "global"
    files: 
      - ".cursor/shared-state/**"
      - "**/*任務清單*.md"
      - "**/*開發計畫*.md"
      - "**/CHANGELOG.md"
    responsibilities:
      - "conflict_resolution"
      - "priority_management"
      - "global_coordination"
    
  project_manager:
    priority: "high"
    authority_level: "project"
    files:
      - "**/Qubic_AI_Compute_Layer_詳細任務清單.md"
      - "**/開發日誌.md"
      - "workspaces/pm-workspace/**"
      - ".cursor/shared-state/task-board.md"
    responsibilities:
      - "progress_tracking"
      - "milestone_management"
      - "resource_planning"
    
  development_team:
    priority: "high"
    authority_level: "technical"
    files:
      - "src/**"
      - "backend/**"
      - "frontend/**"
      - "*.py"
      - "*.js"
      - "*.ts"
      - "requirements.txt"
      - "package.json"
    excluded_files:
      - "tests/**"
      - "docs/**"
      - "docker/**"
    responsibilities:
      - "code_development"
      - "architecture_design"
      - "technical_decisions"
    
  testing_team:
    priority: "medium"
    authority_level: "quality"
    files:
      - "tests/**"
      - "**/test_*.py"
      - "**/test_*.js"
      - "pytest.ini"
      - "jest.config.js"
    watch_files:
      - "src/**"
      - "backend/**"
      - "frontend/**"
    responsibilities:
      - "quality_assurance"
      - "test_automation"
      - "defect_tracking"
    
  documentation_team:
    priority: "medium"
    authority_level: "content"
    files:
      - "docs/**"
      - "*.md"
      - "README*"
      - "CHANGELOG*"
      - "workspaces/doc-workspace/**"
    watch_files:
      - "src/**"
      - "backend/**"
      - "frontend/**"
      - "tests/**"
    responsibilities:
      - "documentation_maintenance"
      - "knowledge_management"
      - "content_quality"
    
  devops_team:
    priority: "medium"
    authority_level: "infrastructure"
    files:
      - "docker/**"
      - ".github/**"
      - "*.yml"
      - "*.yaml"
      - "scripts/**"
      - "terraform/**"
      - "kubernetes/**"
    responsibilities:
      - "infrastructure_management"
      - "deployment_automation"
      - "monitoring_setup"

# 衝突解決規則
conflict_resolution:
  rules:
    file_conflicts:
      detection: "automatic_on_save"
      resolution_strategy: "merge_with_coordinator_review"
      escalation_timeout: "10 minutes"
      
    priority_conflicts:
      detection: "task_assignment_overlap"
      resolution_strategy: "coordinator_arbitration"
      escalation_timeout: "5 minutes"
      
    resource_conflicts:
      detection: "concurrent_file_access"
      resolution_strategy: "queue_based_access"
      escalation_timeout: "2 minutes"
      
    deadline_conflicts:
      detection: "milestone_dependency_violation"
      resolution_strategy: "project_manager_adjustment"
      escalation_timeout: "1 hour"
  
  escalation_hierarchy:
    1. "automatic_resolution"
    2. "team_lead_intervention"
    3. "central_coordinator_arbitration"
    4. "human_escalation"

# 工作時間和可用性
working_hours:
  central_coordinator:
    schedule: "24/7"
    timezone: "UTC"
    emergency_response: "immediate"
    
  project_manager:
    schedule: "09:00-18:00"
    timezone: "Asia/Taipei"
    emergency_response: "within_2_hours"
    
  development_team:
    schedule: "09:00-18:00"
    timezone: "Asia/Taipei"
    emergency_response: "within_1_hour"
    
  testing_team:
    schedule: "09:00-18:00"
    timezone: "Asia/Taipei"
    emergency_response: "within_4_hours"
    
  documentation_team:
    schedule: "09:00-18:00"
    timezone: "Asia/Taipei"
    emergency_response: "next_business_day"
    
  devops_team:
    schedule: "24/7_on_call"
    timezone: "Asia/Taipei"
    emergency_response: "within_30_minutes"

# 品質控制和指標
quality_control:
  sync_success_rate: ">98%"
  conflict_resolution_time: "<10_minutes"
  communication_response_time: "<5_minutes"
  task_completion_accuracy: ">95%"
  
monitoring:
  sync_health_check: "every_minute"
  agent_activity_tracking: "continuous"
  performance_metrics: "hourly_reports"
  error_logging: "comprehensive"
  
alerts:
  sync_failure: "immediate"
  agent_unresponsive: "after_10_minutes"
  conflict_unresolved: "after_30_minutes"
  milestone_risk: "daily_notification"

# 安全和權限
security:
  file_access_control: "role_based"
  sensitive_files_protection: "coordinator_only"
  audit_trail: "all_changes_logged"
  backup_frequency: "hourly"
  
permissions:
  read_only_files:
    - ".cursor/multi-agent-config/**"
    - "LICENSE"
    
  protected_files:
    - ".cursor/shared-state/project-state.json"
    - ".cursor/shared-state/conflicts.md"
    - ".cursor/shared-state/decisions.md"
    
  collaborative_files:
    - ".cursor/shared-state/task-board.md"
    - ".cursor/shared-state/daily-standup.md"

# 自動化和腳本
automation:
  sync_monitor_script: "scripts/sync-monitor.py"
  conflict_detector: "scripts/conflict-detector.py"
  progress_tracker: "scripts/progress-tracker.py"
  notification_system: "scripts/notification-manager.py"
  
scheduled_tasks:
  daily_standup_preparation: "08:30_daily"
  weekly_progress_report: "friday_17:00"
  monthly_metrics_analysis: "last_friday_month"
  backup_verification: "sunday_02:00"
